"""empty message

Revision ID: 11c085f2d755
Revises: b60d7c8bd906
Create Date: 2022-09-06 12:57:45.281757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c085f2d755'
down_revision = 'b60d7c8bd906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_data', sa.Column('game_id', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_data', 'game_id')
    # ### end Alembic commands ###
