"""empty message

Revision ID: b60d7c8bd906
Revises: af4efcaeacb1
Create Date: 2022-09-04 19:29:25.294034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60d7c8bd906'
down_revision = 'af4efcaeacb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=150), nullable=False),
    sa.Column('match_up', sa.String(length=300), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('favorite', sa.String(length=150), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_data')
    # ### end Alembic commands ###
